inherit_from:
  - .rubocop_airbnb.yml

# 文字数上限
LineLength:
  Max: 130
  
# devise
Airbnb/ClassOrModuleDeclaredInWrongFile:
  Exclude:
    - 'app/controllers/admin/*'
    - 'app/controllers/public/*'
#ここにはrubocopでコード解析したくないファイルやフォルダを指定します
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'